services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: on-failure
    environment:
      - JENKINS_EXT_URL
      - JENKINS_AGENT_PRIVATEKEY

  ssh-agent:
    image: jenkins/ssh-agent:jdk17
    environment:
      - JENKINS_AGENT_SSH_PUBKEY="${JENKINS_AGENT_SSH_PUBKEY}"
    restart: on-failure

volumes:
  jenkins_home: